const wordle = ["REACT", "MODEM", "CACHE", "VIRUS", "EMAIL", "ASCII", "ABORT", "BASIC", "DEBUG", "BLOCK", "ERASE", "FLASH", "IMAGE", "VIDEO", "GATES",  
    "LOGIC", "LOGIN", "MICRO", "LAYER", "INTEL", "MSDOS", "PIXEL", "PROXY", "RESET", "QUEUE", "ROBOT", "QUERY", "SPOOL", "STACK", "TABLE", 
    "WRITE", "POPUP", "FORUM", "EPROM", "CRASH", "COBOL", "CLICK", "ALGOL", "ARIAL", "ADDON", "ADDIN", "CORAL", "CLOSE", "FIELD", "FRAME", 
    "MEDIA", "PATCH", "OCTAL", "TRACK", "LABEL", "SABER", "ABAND", "ADOBE", "NOTCH", "BYTES", "CORES", "ARRAY", "HYDRA", "GRAPH", "TREES", 
    "MULTI", "PROTO", "STATS", "HEAPS", "WIDTH", "MOUNT", "COBOL", "CLONE", "OCCAM", "WHILE", "CABLE", "ERROR", "TRIAL", "SOAPS", "TRAMS", 
    "CLASS", "LOOPS", "YANNI", "OKAPI", "TURBO", "FLOAT", "FAULT", "MORPH", "MOUSE", "MILLI", "VUEJS", "CONST", "FINAL", "SCOPE", "LAMDA", 
    "MERGE", "BREAK", "MODEL", "INPUT", "TRAIN", "MYSQL", "SHORT", "UNION", "THROW", "CATCH", "USING", "PRINT", "YEILD", "RAISE", "SUPER"];